# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driver_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1402, 736)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid #000;\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QFrame.WinPanel)
        self.main_header.setFrameShadow(QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QFrame(self.main_header)
        self.tittle_bar_container.setFrameShape(QFrame.StyledPanel)
        self.tittle_bar_container.setFrameShadow(QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_5 = QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QSize(50, 16777215))
        self.left_menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_menu_toggle.setFrameShape(QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_menu_toggle_btn = QPushButton(self.left_menu_toggle)
        self.left_menu_toggle_btn.setMinimumSize(QSize(0, 50))
        self.left_menu_toggle_btn.setMaximumSize(QSize(50, 16777215))
        self.left_menu_toggle_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.left_menu_toggle_btn.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/icons/cil-menu.png"), QIcon.Normal, QIcon.Off)
        self.left_menu_toggle_btn.setIcon(icon)
        self.left_menu_toggle_btn.setIconSize(QSize(24, 24))
        self.left_menu_toggle_btn.setObjectName("left_menu_toggle_btn")
        self.horizontalLayout_4.addWidget(self.left_menu_toggle_btn)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.tittle_bar = QFrame(self.tittle_bar_container)
        self.tittle_bar.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.tittle_bar.setFrameShape(QFrame.StyledPanel)
        self.tittle_bar.setFrameShadow(QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.verticalLayout_9 = QVBoxLayout(self.tittle_bar)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QLabel(self.tittle_bar)
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.top_right_btns.setFrameShape(QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.restoreButton = QPushButton(self.top_right_btns)
        self.restoreButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.restoreButton.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/icons/cil-window-maximize.png"), QIcon.Normal, QIcon.Off)
        self.restoreButton.setIcon(icon1)
        self.restoreButton.setIconSize(QSize(24, 24))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_3.addWidget(self.restoreButton)
        self.minimizeButton = QPushButton(self.top_right_btns)
        self.minimizeButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.minimizeButton.setText("")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/icons/icons/cil-minus.png"), QIcon.Normal, QIcon.Off)
        self.minimizeButton.setIcon(icon2)
        self.minimizeButton.setIconSize(QSize(24, 24))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.closeButton = QPushButton(self.top_right_btns)
        self.closeButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.closeButton.setText("")
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/icons/icons/cil-x.png"), QIcon.Normal, QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QFrame(self.centralwidget)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QFrame.StyledPanel)
        self.main_body.setFrameShadow(QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QFrame(self.main_body)
        self.left_side_menu.setMaximumSize(QSize(50, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 20px 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(0, 92, 157);\n"
"    border-bottom: 2px solid rgb(255, 165, 24);\n"
"}")
        self.left_side_menu.setFrameShape(QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_3 = QVBoxLayout(self.left_side_menu)
        self.verticalLayout_3.setContentsMargins(7, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.left_menu_top_buttons = QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setFrameShape(QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.accounts_button = QPushButton(self.left_menu_top_buttons)
        self.accounts_button.setGeometry(QRect(1, 54, 131, 53))
        self.accounts_button.setMinimumSize(QSize(100, 0))
        self.accounts_button.setStyleSheet("background-image: url(:/icons/icons/cil-user.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.accounts_button.setObjectName("accounts_button")
        self.home_button = QPushButton(self.left_menu_top_buttons)
        self.home_button.setGeometry(QRect(1, 1, 131, 53))
        self.home_button.setMinimumSize(QSize(100, 0))
        self.home_button.setStyleSheet("background-image: url(:/icons/icons/cil-home.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.home_button.setObjectName("home_button")
        self.btnaddNewDriver = QPushButton(self.left_menu_top_buttons)
        self.btnaddNewDriver.setEnabled(False)
        self.btnaddNewDriver.setGeometry(QRect(0, 110, 131, 53))
        self.btnaddNewDriver.setMinimumSize(QSize(100, 0))
        self.btnaddNewDriver.setStyleSheet("background-image:url(:/icons/icons/cil-medical-cross.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.btnaddNewDriver.setObjectName("btnaddNewDriver")

        self.btnPriewWin = QPushButton(self.left_menu_top_buttons)
        self.btnPriewWin.setEnabled(False)
        self.btnPriewWin.setGeometry(QRect(0, 170, 131, 53))
        self.btnPriewWin.setMinimumSize(QSize(100, 0))
        self.btnPriewWin.setStyleSheet("background-image:url(:/icons/icons/cil-airplay.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.btnPriewWin.setObjectName("btnPriewWin")
        self.btnAddNewUser = QPushButton(self.left_menu_top_buttons)
        self.btnAddNewUser.setEnabled(False)
        self.btnAddNewUser.setGeometry(QRect(0, 230, 131, 53))
        self.btnAddNewUser.setMinimumSize(QSize(100, 0))
        self.btnAddNewUser.setStyleSheet("background-image:url(:/icons/icons/cil-user-follow.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.btnAddNewUser.setObjectName("btnAddNewUser")
        self.btnAddNewBooking = QPushButton(self.left_menu_top_buttons)
        self.btnAddNewBooking.setEnabled(False)
        self.btnAddNewBooking.setGeometry(QRect(0, 290, 131, 53))
        self.btnAddNewBooking.setMinimumSize(QSize(100, 0))
        self.btnAddNewBooking.setStyleSheet("background-image:url(:/icons/icons/cil-task.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.btnAddNewBooking.setObjectName("btnAddNewBooking")
        self.verticalLayout_3.addWidget(self.left_menu_top_buttons)
        self.btnShutdown = QPushButton(self.left_side_menu)
        self.btnShutdown.setMinimumSize(QSize(100, 0))
        self.btnShutdown.setStyleSheet("background-image:url(:/icons/icons/cil-moon.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.btnShutdown.setObjectName("btnShutdown")
        self.verticalLayout_3.addWidget(self.btnShutdown)
        self.settings_button = QPushButton(self.left_side_menu)
        self.settings_button.setEnabled(False)
        self.settings_button.setMinimumSize(QSize(100, 0))
        self.settings_button.setStyleSheet("background-image: url(:/icons/icons/cil-settings.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_3.addWidget(self.settings_button)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_items = QFrame(self.main_body)
        self.center_main_items.setStyleSheet("")
        self.center_main_items.setFrameShape(QFrame.StyledPanel)
        self.center_main_items.setFrameShadow(QFrame.Raised)
        self.center_main_items.setObjectName("center_main_items")
        self.verticalLayout_2 = QVBoxLayout(self.center_main_items)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QStackedWidget(self.center_main_items)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QWidget()
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.verticalLayout_7 = QVBoxLayout(self.home_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget.addWidget(self.home_page)
        self.accounts_page = QWidget()
        self.accounts_page.setStyleSheet("")
        self.accounts_page.setObjectName("accounts_page")
        self.verticalLayout_6 = QVBoxLayout(self.accounts_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.login_form_frame = QFrame(self.accounts_page)
        self.login_form_frame.setMinimumSize(QSize(450, 350))
        self.login_form_frame.setMaximumSize(QSize(450, 350))
        self.login_form_frame.setStyleSheet("border-radius: 20px;\n"
"")
        self.login_form_frame.setFrameShape(QFrame.StyledPanel)
        self.login_form_frame.setFrameShadow(QFrame.Raised)
        self.login_form_frame.setObjectName("login_form_frame")
        self.input_fileds_frame = QFrame(self.login_form_frame)
        self.input_fileds_frame.setGeometry(QRect(50, 20, 328, 310))
        self.input_fileds_frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame.setFrameShape(QFrame.StyledPanel)
        self.input_fileds_frame.setFrameShadow(QFrame.Raised)
        self.input_fileds_frame.setObjectName("input_fileds_frame")
        self.label_2 = QLabel(self.input_fileds_frame)
        self.label_2.setGeometry(QRect(11, 97, 100, 50))
        self.label_2.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.uname_2 = QLineEdit(self.input_fileds_frame)
        self.uname_2.setGeometry(QRect(117, 97, 200, 52))
        self.uname_2.setMinimumSize(QSize(200, 50))
        self.uname_2.setMaximumSize(QSize(200, 16777215))
        self.uname_2.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.uname_2.setAlignment(Qt.AlignCenter)
        self.uname_2.setObjectName("uname_2")
        self.label_5 = QLabel(self.input_fileds_frame)
        self.label_5.setGeometry(QRect(11, 155, 100, 50))
        self.label_5.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.password_2 = QLineEdit(self.input_fileds_frame)
        self.password_2.setGeometry(QRect(117, 155, 200, 52))
        self.password_2.setMinimumSize(QSize(200, 50))
        self.password_2.setMaximumSize(QSize(200, 16777215))
        self.password_2.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.password_2.setEchoMode(QLineEdit.Password)
        self.password_2.setAlignment(Qt.AlignCenter)
        self.password_2.setObjectName("password_2")
        self.checkBox = QCheckBox(self.input_fileds_frame)
        self.checkBox.setGeometry(QRect(170, 230, 141, 46))
        self.checkBox.setObjectName("checkBox")
        self.btnLogIn = QPushButton(self.input_fileds_frame)
        self.btnLogIn.setGeometry(QRect(20, 230, 141, 50))
        self.btnLogIn.setMinimumSize(QSize(0, 50))
        self.btnLogIn.setMaximumSize(QSize(200, 16777215))
        self.btnLogIn.setObjectName("btnLogIn")
        self.profile_icon_frame = QFrame(self.input_fileds_frame)
        self.profile_icon_frame.setGeometry(QRect(30, 30, 50, 50))
        self.profile_icon_frame.setMinimumSize(QSize(50, 50))
        self.profile_icon_frame.setMaximumSize(QSize(50, 50))
        self.profile_icon_frame.setStyleSheet("image: url(:/icons/icons/cil-user-follow.png);\n"
"background-color: rgb(34, 34, 34);\n"
"border-radius: 25px;\n"
"border: 3px solid rgb(0, 93, 159);")
        self.profile_icon_frame.setFrameShape(QFrame.StyledPanel)
        self.profile_icon_frame.setFrameShadow(QFrame.Raised)
        self.profile_icon_frame.setObjectName("profile_icon_frame")
        self.label_33 = QLabel(self.input_fileds_frame)
        self.label_33.setGeometry(QRect(80, 40, 51, 31))
        self.label_33.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_6.addWidget(self.login_form_frame, 0, Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.accounts_page)
        self.NewDriver_page = QWidget()
        self.NewDriver_page.setObjectName("NewDriver_page")
        self.verticalLayout_4 = QVBoxLayout(self.NewDriver_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.login_form_widget_2 = QWidget(self.NewDriver_page)
        self.login_form_widget_2.setEnabled(True)
        self.login_form_widget_2.setMinimumSize(QSize(450, 350))
        self.login_form_widget_2.setMaximumSize(QSize(450, 350))
        self.login_form_widget_2.setStyleSheet("border-radius: 20px;\n"
"")
        self.login_form_widget_2.setObjectName("login_form_widget_2")
        self.input_fileds_frame_2 = QFrame(self.login_form_widget_2)
        self.input_fileds_frame_2.setGeometry(QRect(0, 0, 441, 332))
        self.input_fileds_frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame_2.setFrameShape(QFrame.StyledPanel)
        self.input_fileds_frame_2.setFrameShadow(QFrame.Raised)
        self.input_fileds_frame_2.setObjectName("input_fileds_frame_2")
        self.label_8 = QLabel(self.input_fileds_frame_2)
        self.label_8.setGeometry(QRect(10, 10, 100, 50))
        self.label_8.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QLineEdit(self.input_fileds_frame_2)
        self.lineEdit_3.setGeometry(QRect(110, 10, 200, 52))
        self.lineEdit_3.setMinimumSize(QSize(200, 50))
        self.lineEdit_3.setMaximumSize(QSize(200, 16777215))
        self.lineEdit_3.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.lineEdit_3.setAlignment(Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QLabel(self.input_fileds_frame_2)
        self.label_9.setGeometry(QRect(10, 60, 100, 50))
        self.label_9.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_4 = QLineEdit(self.input_fileds_frame_2)
        self.lineEdit_4.setGeometry(QRect(110, 60, 200, 52))
        self.lineEdit_4.setMinimumSize(QSize(200, 50))
        self.lineEdit_4.setMaximumSize(QSize(200, 16777215))
        self.lineEdit_4.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.lineEdit_4.setEchoMode(QLineEdit.Normal)
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.btnSaveDriver = QPushButton(self.input_fileds_frame_2)
        self.btnSaveDriver.setGeometry(QRect(320, 260, 101, 50))
        self.btnSaveDriver.setMinimumSize(QSize(0, 50))
        self.btnSaveDriver.setMaximumSize(QSize(200, 16777215))
        self.btnSaveDriver.setObjectName("btnSaveDriver")
        self.profile_icon_frame_2 = QFrame(self.input_fileds_frame_2)
        self.profile_icon_frame_2.setGeometry(QRect(310, 10, 50, 50))
        self.profile_icon_frame_2.setMinimumSize(QSize(50, 50))
        self.profile_icon_frame_2.setMaximumSize(QSize(50, 50))
        self.profile_icon_frame_2.setStyleSheet("image: url(:/icons/icons/cil-user-follow.png);\n"
"background-color: rgb(34, 34, 34);\n"
"border-radius: 25px;\n"
"border: 3px solid rgb(0, 93, 159);")
        self.profile_icon_frame_2.setFrameShape(QFrame.StyledPanel)
        self.profile_icon_frame_2.setFrameShadow(QFrame.Raised)
        self.profile_icon_frame_2.setObjectName("profile_icon_frame_2")
        self.label_10 = QLabel(self.input_fileds_frame_2)
        self.label_10.setGeometry(QRect(10, 110, 100, 52))
        self.label_10.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.driverphoneNum = QLineEdit(self.input_fileds_frame_2)
        self.driverphoneNum.setGeometry(QRect(110, 160, 200, 52))
        self.driverphoneNum.setMinimumSize(QSize(200, 50))
        self.driverphoneNum.setMaximumSize(QSize(200, 16777215))
        self.driverphoneNum.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.driverphoneNum.setAlignment(Qt.AlignCenter)
        self.driverphoneNum.setObjectName("driverphoneNum")
        self.label_11 = QLabel(self.input_fileds_frame_2)
        self.label_11.setGeometry(QRect(10, 160, 100, 52))
        self.label_11.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.driverEmail = QLineEdit(self.input_fileds_frame_2)
        self.driverEmail.setGeometry(QRect(110, 210, 200, 52))
        self.driverEmail.setMinimumSize(QSize(200, 50))
        self.driverEmail.setMaximumSize(QSize(200, 16777215))
        self.driverEmail.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.driverEmail.setEchoMode(QLineEdit.Password)
        self.driverEmail.setAlignment(Qt.AlignCenter)
        self.driverEmail.setObjectName("driverEmail")
        self.label_12 = QLabel(self.input_fileds_frame_2)
        self.label_12.setGeometry(QRect(10, 210, 100, 52))
        self.label_12.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.btnCaptureDriverPic = QPushButton(self.input_fileds_frame_2)
        self.btnCaptureDriverPic.setGeometry(QRect(320, 200, 101, 50))
        self.btnCaptureDriverPic.setMinimumSize(QSize(0, 50))
        self.btnCaptureDriverPic.setMaximumSize(QSize(200, 16777215))
        self.btnCaptureDriverPic.setObjectName("btnCaptureDriverPic")
        self.driverPic = QLabel(self.input_fileds_frame_2)
        self.driverPic.setGeometry(QRect(320, 80, 101, 101))
        self.driverPic.setStyleSheet("background:url(:/icons/icons/cil-satelite.png);")
        self.driverPic.setText("")
        self.driverPic.setObjectName("driverPic")
        self.label_37 = QLabel(self.input_fileds_frame_2)
        self.label_37.setGeometry(QRect(10, 260, 100, 52))
        self.label_37.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("")
        self.label_37.setAlignment(Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.driverAddress = QLineEdit(self.input_fileds_frame_2)
        self.driverAddress.setGeometry(QRect(110, 260, 200, 52))
        self.driverAddress.setMinimumSize(QSize(200, 50))
        self.driverAddress.setMaximumSize(QSize(200, 16777215))
        self.driverAddress.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.driverAddress.setEchoMode(QLineEdit.Password)
        self.driverAddress.setAlignment(Qt.AlignCenter)
        self.driverAddress.setObjectName("driverAddress")
        self.dateEdit = QDateEdit(self.input_fileds_frame_2)
        self.dateEdit.setGeometry(QRect(120, 120, 181, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(0, 69, 116);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_40 = QLabel(self.input_fileds_frame_2)
        self.label_40.setGeometry(QRect(360, 20, 81, 31))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_4.addWidget(self.login_form_widget_2, 0, Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.NewDriver_page)
        self.prieviewWin_page = QWidget()
        self.prieviewWin_page.setObjectName("prieviewWin_page")
        self.frame = QFrame(self.prieviewWin_page)
        self.frame.setGeometry(QRect(-10, 0, 1321, 611))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.input_fileds_frame_3 = QFrame(self.frame)
        self.input_fileds_frame_3.setMinimumSize(QSize(851, 581))
        self.input_fileds_frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame_3.setObjectName("input_fileds_frame_3")
        self.profile_icon_frame_4 = QFrame(self.input_fileds_frame_3)
        self.profile_icon_frame_4.setGeometry(QRect(1210, 490, 50, 50))
        self.profile_icon_frame_4.setMinimumSize(QSize(50, 50))
        self.profile_icon_frame_4.setMaximumSize(QSize(50, 50))
        self.profile_icon_frame_4.setStyleSheet("image: url(:/icons/icons/cil-user-follow.png);\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius: 25px;\n"
"border: 3px solid rgb(0, 93, 159);")
        self.profile_icon_frame_4.setFrameShape(QFrame.StyledPanel)
        self.profile_icon_frame_4.setFrameShadow(QFrame.Raised)
        self.profile_icon_frame_4.setObjectName("profile_icon_frame_4")
        self.btnObjDec = QPushButton(self.input_fileds_frame_3)
        self.btnObjDec.setGeometry(QRect(170, 530, 141, 50))
        self.btnObjDec.setMinimumSize(QSize(0, 50))
        self.btnObjDec.setMaximumSize(QSize(200, 16777215))
        self.btnObjDec.setObjectName("btnObjDec")
        self.pipelineVideoView_2 = QLabel(self.input_fileds_frame_3)
        self.pipelineVideoView_2.setGeometry(QRect(0, 0, 651, 481))
        self.pipelineVideoView_2.setText("")
        self.pipelineVideoView_2.setObjectName("pipelineVideoView_2")
        self.btnPause = QPushButton(self.input_fileds_frame_3)
        self.btnPause.setGeometry(QRect(170, 480, 141, 50))
        self.btnPause.setMinimumSize(QSize(0, 50))
        self.btnPause.setMaximumSize(QSize(200, 16777215))
        self.btnPause.setObjectName("btnPause")
        self.btnView = QPushButton(self.input_fileds_frame_3)
        self.btnView.setGeometry(QRect(30, 480, 141, 50))
        self.btnView.setMinimumSize(QSize(0, 50))
        self.btnView.setMaximumSize(QSize(200, 16777215))
        self.btnView.setObjectName("btnView")
        self.btnLane = QPushButton(self.input_fileds_frame_3)
        self.btnLane.setGeometry(QRect(30, 530, 141, 50))
        self.btnLane.setMinimumSize(QSize(0, 50))
        self.btnLane.setMaximumSize(QSize(200, 16777215))
        self.btnLane.setObjectName("btnLane")
        self.label_19 = QLabel(self.input_fileds_frame_3)
        self.label_19.setGeometry(QRect(1110, 490, 91, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(34, 34, 34);")
        self.label_19.setObjectName("label_19")
        self.btnTrafficSigns = QPushButton(self.input_fileds_frame_3)
        self.btnTrafficSigns.setGeometry(QRect(310, 530, 141, 50))
        self.btnTrafficSigns.setMinimumSize(QSize(0, 50))
        self.btnTrafficSigns.setMaximumSize(QSize(200, 16777215))
        self.btnTrafficSigns.setObjectName("btnTrafficSigns")
        self.label_20 = QLabel(self.input_fileds_frame_3)
        self.label_20.setGeometry(QRect(650, 520, 111, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(34, 34, 34);\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QLabel(self.input_fileds_frame_3)
        self.label_21.setGeometry(QRect(650, 540, 101, 21))
        self.label_21.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QLabel(self.input_fileds_frame_3)
        self.label_22.setGeometry(QRect(650, 560, 101, 21))
        self.label_22.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QLabel(self.input_fileds_frame_3)
        self.label_23.setGeometry(QRect(810, 540, 111, 21))
        self.label_23.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QLabel(self.input_fileds_frame_3)
        self.label_24.setGeometry(QRect(810, 560, 111, 21))
        self.label_24.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.label_24.setObjectName("label_24")
        self.lanekeeping = QLabel(self.input_fileds_frame_3)
        self.lanekeeping.setGeometry(QRect(750, 540, 61, 21))
        self.lanekeeping.setObjectName("lanekeeping")
        self.lights = QLabel(self.input_fileds_frame_3)
        self.lights.setGeometry(QRect(750, 560, 61, 21))
        self.lights.setObjectName("lights")
        self.speeding = QLabel(self.input_fileds_frame_3)
        self.speeding.setGeometry(QRect(940, 560, 81, 21))
        self.speeding.setObjectName("speeding")
        self.stopsign = QLabel(self.input_fileds_frame_3)
        self.stopsign.setGeometry(QRect(940, 540, 81, 21))
        self.stopsign.setObjectName("stopsign")
        self.Totalpoints = QLabel(self.input_fileds_frame_3)
        self.Totalpoints.setGeometry(QRect(1210, 540, 61, 21))
        self.Totalpoints.setObjectName("Totalpoints")
        self.label_34 = QLabel(self.input_fileds_frame_3)
        self.label_34.setGeometry(QRect(1110, 540, 101, 21))
        self.label_34.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_34.setObjectName("label_34")
        self.testDeciscion = QLabel(self.input_fileds_frame_3)
        self.testDeciscion.setGeometry(QRect(1210, 560, 61, 21))
        self.testDeciscion.setObjectName("testDeciscion")
        self.label_36 = QLabel(self.input_fileds_frame_3)
        self.label_36.setGeometry(QRect(1110, 560, 101, 21))
        self.label_36.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_36.setObjectName("label_36")
        self.Drivernamelbl = QLabel(self.input_fileds_frame_3)
        self.Drivernamelbl.setGeometry(QRect(1110, 510, 81, 21))
        self.Drivernamelbl.setStyleSheet("\n"
"background-color: rgb(34, 34, 34);")
        self.Drivernamelbl.setObjectName("Drivernamelbl")
        self.btnTrafficLights = QPushButton(self.input_fileds_frame_3)
        self.btnTrafficLights.setGeometry(QRect(450, 530, 141, 50))
        self.btnTrafficLights.setMinimumSize(QSize(0, 50))
        self.btnTrafficLights.setMaximumSize(QSize(200, 16777215))
        self.btnTrafficLights.setObjectName("btnTrafficLights")
        self.label_45 = QLabel(self.input_fileds_frame_3)
        self.label_45.setGeometry(QRect(650, 480, 101, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: rgb(255, 0, 0);\n"
"font-color : rgb(34, 34, 34);\n"
"border-color: rgb(34, 34, 34);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QLabel(self.input_fileds_frame_3)
        self.label_46.setGeometry(QRect(650, 500, 71, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: rgb(255, 0, 0);\n"
"border-color: rgb(34, 34, 34);")
        self.label_46.setObjectName("label_46")
        self.label_47 = QLabel(self.input_fileds_frame_3)
        self.label_47.setGeometry(QRect(810, 480, 141, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: rgb(255, 0, 0);\n"
"border-color: rgb(34, 34, 34);")
        self.label_47.setObjectName("label_47")
        self.label_48 = QLabel(self.input_fileds_frame_3)
        self.label_48.setGeometry(QRect(810, 500, 141, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: rgb(255, 0, 0);\n"
"border-color: rgb(34, 34, 34);")
        self.label_48.setObjectName("label_48")
        self.maxSpeedlbl = QLabel(self.input_fileds_frame_3)
        self.maxSpeedlbl.setGeometry(QRect(730, 480, 81, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxSpeedlbl.setFont(font)
        self.maxSpeedlbl.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.maxSpeedlbl.setObjectName("maxSpeedlbl")
        self.headinglbl = QLabel(self.input_fileds_frame_3)
        self.headinglbl.setGeometry(QRect(730, 500, 81, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.headinglbl.setFont(font)
        self.headinglbl.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.headinglbl.setObjectName("headinglbl")
        self.maxAccellbl = QLabel(self.input_fileds_frame_3)
        self.maxAccellbl.setGeometry(QRect(940, 480, 81, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxAccellbl.setFont(font)
        self.maxAccellbl.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.maxAccellbl.setObjectName("maxAccellbl")
        self.distanceCovlbl = QLabel(self.input_fileds_frame_3)
        self.distanceCovlbl.setGeometry(QRect(940, 500, 81, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.distanceCovlbl.setFont(font)
        self.distanceCovlbl.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.distanceCovlbl.setObjectName("distanceCovlbl")
        self.BtnprocessResults = QPushButton(self.input_fileds_frame_3)
        self.BtnprocessResults.setGeometry(QRect(450, 480, 141, 50))
        self.BtnprocessResults.setMinimumSize(QSize(0, 50))
        self.BtnprocessResults.setMaximumSize(QSize(200, 16777215))
        self.BtnprocessResults.setObjectName("BtnprocessResults")
        self.distancePlot_2 = PlotWidget(self.input_fileds_frame_3)
        self.distancePlot_2.setGeometry(QRect(650, 230, 331, 251))
        self.distancePlot_2.setObjectName("distancePlot_2")
        self.label_16 = QLabel(self.distancePlot_2)
        self.label_16.setGeometry(QRect(0, 0, 141, 21))
        self.label_16.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_16.setObjectName("label_16")
        self.LinearAccelerationPlot_2 = PlotWidget(self.input_fileds_frame_3)
        self.LinearAccelerationPlot_2.setGeometry(QRect(650, 0, 331, 231))
        self.LinearAccelerationPlot_2.setObjectName("LinearAccelerationPlot_2")
        self.label_18 = QLabel(self.LinearAccelerationPlot_2)
        self.label_18.setGeometry(QRect(0, 0, 181, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_18.setObjectName("label_18")
        self.LinearAccelerationPlot_3 = PlotWidget(self.input_fileds_frame_3)
        self.LinearAccelerationPlot_3.setGeometry(QRect(980, 0, 321, 231))
        self.LinearAccelerationPlot_3.setObjectName("LinearAccelerationPlot_3")
        self.label_35 = QLabel(self.LinearAccelerationPlot_3)
        self.label_35.setGeometry(QRect(0, 0, 181, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_35.setObjectName("label_35")
        self.speedVariaitionPlot = PlotWidget(self.input_fileds_frame_3)
        self.speedVariaitionPlot.setGeometry(QRect(980, 230, 321, 251))
        self.speedVariaitionPlot.setObjectName("speedVariaitionPlot")
        self.label_44 = QLabel(self.speedVariaitionPlot)
        self.label_44.setGeometry(QRect(0, 0, 141, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_44.setObjectName("label_44")
        self.btnPipelineView_2 = QPushButton(self.input_fileds_frame_3)
        self.btnPipelineView_2.setGeometry(QRect(310, 480, 141, 50))
        self.btnPipelineView_2.setMinimumSize(QSize(0, 50))
        self.btnPipelineView_2.setMaximumSize(QSize(200, 16777215))
        self.btnPipelineView_2.setObjectName("btnPipelineView_2")
        self.gridLayout_7.addWidget(self.input_fileds_frame_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.prieviewWin_page)
        self.addNewUser_page = QWidget()
        self.addNewUser_page.setObjectName("addNewUser_page")
        self.gridLayout_4 = QGridLayout(self.addNewUser_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.login_form_widget_3 = QWidget(self.addNewUser_page)
        self.login_form_widget_3.setMinimumSize(QSize(450, 350))
        self.login_form_widget_3.setMaximumSize(QSize(450, 350))
        self.login_form_widget_3.setStyleSheet("border-radius: 20px;\n"
"")
        self.login_form_widget_3.setObjectName("login_form_widget_3")
        self.gridLayout = QGridLayout(self.login_form_widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.input_fileds_frame_4 = QFrame(self.login_form_widget_3)
        self.input_fileds_frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame_4.setFrameShape(QFrame.StyledPanel)
        self.input_fileds_frame_4.setFrameShadow(QFrame.Raised)
        self.input_fileds_frame_4.setObjectName("input_fileds_frame_4")
        self.label_13 = QLabel(self.input_fileds_frame_4)
        self.label_13.setGeometry(QRect(86, 11, 121, 50))
        self.label_13.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.fullname = QLineEdit(self.input_fileds_frame_4)
        self.fullname.setGeometry(QRect(221, 11, 200, 50))
        self.fullname.setMinimumSize(QSize(200, 50))
        self.fullname.setMaximumSize(QSize(200, 16777215))
        self.fullname.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.fullname.setAlignment(Qt.AlignCenter)
        self.fullname.setObjectName("fullname")
        self.profile_icon_frame_3 = QFrame(self.input_fileds_frame_4)
        self.profile_icon_frame_3.setGeometry(QRect(11, 75, 50, 50))
        self.profile_icon_frame_3.setMinimumSize(QSize(50, 50))
        self.profile_icon_frame_3.setMaximumSize(QSize(50, 50))
        self.profile_icon_frame_3.setStyleSheet("image: url(:/icons/icons/cil-user-follow.png);\n"
"background-color: rgb(34, 34, 34);\n"
"border-radius: 25px;\n"
"border: 3px solid rgb(0, 93, 159);")
        self.profile_icon_frame_3.setFrameShape(QFrame.StyledPanel)
        self.profile_icon_frame_3.setFrameShadow(QFrame.Raised)
        self.profile_icon_frame_3.setObjectName("profile_icon_frame_3")
        self.label_14 = QLabel(self.input_fileds_frame_4)
        self.label_14.setGeometry(QRect(86, 63, 121, 50))
        self.label_14.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gender = QLineEdit(self.input_fileds_frame_4)
        self.gender.setGeometry(QRect(221, 63, 200, 50))
        self.gender.setMinimumSize(QSize(200, 50))
        self.gender.setMaximumSize(QSize(200, 16777215))
        self.gender.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.gender.setEchoMode(QLineEdit.Normal)
        self.gender.setAlignment(Qt.AlignCenter)
        self.gender.setObjectName("gender")
        self.label_27 = QLabel(self.input_fileds_frame_4)
        self.label_27.setGeometry(QRect(86, 115, 121, 50))
        self.label_27.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("")
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.uname = QLineEdit(self.input_fileds_frame_4)
        self.uname.setGeometry(QRect(221, 115, 200, 50))
        self.uname.setMinimumSize(QSize(200, 50))
        self.uname.setMaximumSize(QSize(200, 16777215))
        self.uname.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.uname.setAlignment(Qt.AlignCenter)
        self.uname.setObjectName("uname")
        self.label_28 = QLabel(self.input_fileds_frame_4)
        self.label_28.setGeometry(QRect(86, 171, 121, 50))
        self.label_28.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("")
        self.label_28.setAlignment(Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.password = QLineEdit(self.input_fileds_frame_4)
        self.password.setGeometry(QRect(221, 171, 200, 50))
        self.password.setMinimumSize(QSize(200, 50))
        self.password.setMaximumSize(QSize(200, 16777215))
        self.password.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.password.setAlignment(Qt.AlignCenter)
        self.password.setObjectName("password")
        self.label_15 = QLabel(self.input_fileds_frame_4)
        self.label_15.setGeometry(QRect(86, 223, 121, 50))
        self.label_15.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.useremail = QLineEdit(self.input_fileds_frame_4)
        self.useremail.setGeometry(QRect(221, 223, 200, 50))
        self.useremail.setMinimumSize(QSize(200, 50))
        self.useremail.setMaximumSize(QSize(200, 16777215))
        self.useremail.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.useremail.setText("")
        self.useremail.setAlignment(Qt.AlignCenter)
        self.useremail.setObjectName("useremail")
        self.label_32 = QLabel(self.input_fileds_frame_4)
        self.label_32.setGeometry(QRect(11, 143, 69, 19))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("\n"
"background-color: rgb(34, 34, 34);")
        self.label_32.setObjectName("label_32")
        self.btnSaveNewUser = QPushButton(self.input_fileds_frame_4)
        self.btnSaveNewUser.setGeometry(QRect(120, 280, 200, 50))
        self.btnSaveNewUser.setMinimumSize(QSize(0, 50))
        self.btnSaveNewUser.setMaximumSize(QSize(200, 16777215))
        self.btnSaveNewUser.setObjectName("btnSaveNewUser")
        self.gridLayout.addWidget(self.input_fileds_frame_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.login_form_widget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.addNewUser_page)
        self.NewBooking_page = QWidget()
        self.NewBooking_page.setObjectName("NewBooking_page")
        self.gridLayout_5 = QGridLayout(self.NewBooking_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.booking_form_widget_4 = QWidget(self.NewBooking_page)
        self.booking_form_widget_4.setMinimumSize(QSize(450, 350))
        self.booking_form_widget_4.setMaximumSize(QSize(450, 350))
        self.booking_form_widget_4.setStyleSheet("border-radius: 20px;\n"
"")
        self.booking_form_widget_4.setObjectName("booking_form_widget_4")
        self.gridLayout_2 = QGridLayout(self.booking_form_widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_fileds_frame_5 = QFrame(self.booking_form_widget_4)
        self.input_fileds_frame_5.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame_5.setFrameShape(QFrame.StyledPanel)
        self.input_fileds_frame_5.setFrameShadow(QFrame.Raised)
        self.input_fileds_frame_5.setObjectName("input_fileds_frame_5")
        self.label_29 = QLabel(self.input_fileds_frame_5)
        self.label_29.setGeometry(QRect(60, 80, 100, 50))
        self.label_29.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("")
        self.label_29.setAlignment(Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.DriverId = QLineEdit(self.input_fileds_frame_5)
        self.DriverId.setGeometry(QRect(180, 80, 200, 52))
        self.DriverId.setMinimumSize(QSize(200, 50))
        self.DriverId.setMaximumSize(QSize(200, 16777215))
        self.DriverId.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.DriverId.setAlignment(Qt.AlignCenter)
        self.DriverId.setObjectName("DriverId")
        self.label_30 = QLabel(self.input_fileds_frame_5)
        self.label_30.setGeometry(QRect(60, 140, 100, 50))
        self.label_30.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setAlignment(Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.bookDate = QLineEdit(self.input_fileds_frame_5)
        self.bookDate.setGeometry(QRect(180, 140, 200, 52))
        self.bookDate.setMinimumSize(QSize(200, 50))
        self.bookDate.setMaximumSize(QSize(200, 16777215))
        self.bookDate.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.bookDate.setEchoMode(QLineEdit.Normal)
        self.bookDate.setAlignment(Qt.AlignCenter)
        self.bookDate.setObjectName("bookDate")
        self.btnSaveBooking = QPushButton(self.input_fileds_frame_5)
        self.btnSaveBooking.setGeometry(QRect(110, 270, 200, 50))
        self.btnSaveBooking.setMinimumSize(QSize(0, 50))
        self.btnSaveBooking.setMaximumSize(QSize(200, 16777215))
        self.btnSaveBooking.setObjectName("btnSaveBooking")
        self.profile_icon_frame_5 = QFrame(self.input_fileds_frame_5)
        self.profile_icon_frame_5.setGeometry(QRect(20, 20, 50, 50))
        self.profile_icon_frame_5.setMinimumSize(QSize(50, 50))
        self.profile_icon_frame_5.setMaximumSize(QSize(50, 50))
        self.profile_icon_frame_5.setStyleSheet("image: url(:/icons/icons/cil-pin.png);\n"
"background-color: rgb(34, 34, 34);\n"
"border-radius: 25px;\n"
"border: 3px solid rgb(0, 93, 159);")
        self.profile_icon_frame_5.setFrameShape(QFrame.StyledPanel)
        self.profile_icon_frame_5.setFrameShadow(QFrame.Raised)
        self.profile_icon_frame_5.setObjectName("profile_icon_frame_5")
        self.label_31 = QLabel(self.input_fileds_frame_5)
        self.label_31.setGeometry(QRect(60, 200, 100, 52))
        self.label_31.setMinimumSize(QSize(100, 50))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("")
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.licenceClass = QLineEdit(self.input_fileds_frame_5)
        self.licenceClass.setGeometry(QRect(180, 200, 200, 52))
        self.licenceClass.setMinimumSize(QSize(200, 50))
        self.licenceClass.setMaximumSize(QSize(200, 16777215))
        self.licenceClass.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;")
        self.licenceClass.setText("")
        self.licenceClass.setAlignment(Qt.AlignCenter)
        self.licenceClass.setObjectName("licenceClass")
        self.label_3 = QLabel(self.input_fileds_frame_5)
        self.label_3.setGeometry(QRect(70, 30, 91, 31))
        self.label_3.setStyleSheet("\n"
"background-color: rgb(34, 34, 34);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.input_fileds_frame_5, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.booking_form_widget_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.NewBooking_page)
        self.settings_page = QWidget()
        self.settings_page.setStyleSheet("")
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_5 = QVBoxLayout(self.settings_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QLabel(self.settings_page)
        font = QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"color: rgb(0, 85, 255);")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.settings_page)
        self.PipelineView_page = QWidget()
        self.PipelineView_page.setObjectName("PipelineView_page")
        self.frame_2 = QFrame(self.PipelineView_page)
        self.frame_2.setGeometry(QRect(30, 10, 1261, 601))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.input_fileds_frame_6 = QFrame(self.frame_2)
        self.input_fileds_frame_6.setMinimumSize(QSize(851, 581))
        self.input_fileds_frame_6.setStyleSheet("QFrame{\n"
"    background-color: rgb(34, 34, 34);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame_6.setObjectName("input_fileds_frame_6")
        self.profile_icon_frame_6 = QFrame(self.input_fileds_frame_6)
        self.profile_icon_frame_6.setGeometry(QRect(20, 520, 50, 50))
        self.profile_icon_frame_6.setMinimumSize(QSize(50, 50))
        self.profile_icon_frame_6.setMaximumSize(QSize(50, 50))
        self.profile_icon_frame_6.setStyleSheet("image: url(:/icons/icons/cil-video.png);\n"
"background-color: rgb(34, 34, 34);\n"
"border-radius: 25px;\n"
"border: 3px solid rgb(0, 93, 159);")
        self.profile_icon_frame_6.setFrameShape(QFrame.StyledPanel)
        self.profile_icon_frame_6.setFrameShadow(QFrame.Raised)
        self.profile_icon_frame_6.setObjectName("profile_icon_frame_6")
        self.distortedImg = QLabel(self.input_fileds_frame_6)
        self.distortedImg.setGeometry(QRect(0, 0, 411, 261))
        self.distortedImg.setText("")
        self.distortedImg.setObjectName("distortedImg")
        self.label_38 = QLabel(self.input_fileds_frame_6)
        self.label_38.setGeometry(QRect(0, 0, 111, 21))
        self.label_38.setObjectName("label_38")
        self.btnPausePipeline = QPushButton(self.input_fileds_frame_6)
        self.btnPausePipeline.setGeometry(QRect(520, 520, 151, 50))
        self.btnPausePipeline.setMinimumSize(QSize(0, 50))
        self.btnPausePipeline.setMaximumSize(QSize(200, 16777215))
        self.btnPausePipeline.setObjectName("btnPausePipeline")
        self.btnViewPipelineRef = QPushButton(self.input_fileds_frame_6)
        self.btnViewPipelineRef.setGeometry(QRect(370, 520, 151, 50))
        self.btnViewPipelineRef.setMinimumSize(QSize(0, 50))
        self.btnViewPipelineRef.setMaximumSize(QSize(200, 16777215))
        self.btnViewPipelineRef.setObjectName("btnViewPipelineRef")
        self.btnTrafficSigns_2 = QPushButton(self.input_fileds_frame_6)
        self.btnTrafficSigns_2.setGeometry(QRect(670, 520, 181, 50))
        self.btnTrafficSigns_2.setMinimumSize(QSize(0, 50))
        self.btnTrafficSigns_2.setMaximumSize(QSize(200, 16777215))
        self.btnTrafficSigns_2.setObjectName("btnTrafficSigns_2")
        self.pipelineVideoView_4 = QLabel(self.input_fileds_frame_6)
        self.pipelineVideoView_4.setGeometry(QRect(0, 260, 411, 251))
        self.pipelineVideoView_4.setText("")
        self.pipelineVideoView_4.setObjectName("pipelineVideoView_4")
        self.pipelineVideoView_5 = QLabel(self.input_fileds_frame_6)
        self.pipelineVideoView_5.setGeometry(QRect(410, 260, 411, 251))
        self.pipelineVideoView_5.setText("")
        self.pipelineVideoView_5.setObjectName("pipelineVideoView_5")
        self.pipelineVideoView_6 = QLabel(self.input_fileds_frame_6)
        self.pipelineVideoView_6.setGeometry(QRect(410, 0, 411, 261))
        self.pipelineVideoView_6.setText("")
        self.pipelineVideoView_6.setObjectName("pipelineVideoView_6")
        self.pipelineVideoView_7 = QLabel(self.input_fileds_frame_6)
        self.pipelineVideoView_7.setGeometry(QRect(820, 260, 421, 251))
        self.pipelineVideoView_7.setText("")
        self.pipelineVideoView_7.setObjectName("pipelineVideoView_7")
        self.pipelineVideoView_8 = QLabel(self.input_fileds_frame_6)
        self.pipelineVideoView_8.setGeometry(QRect(820, 0, 421, 261))
        self.pipelineVideoView_8.setText("")
        self.pipelineVideoView_8.setObjectName("pipelineVideoView_8")
        self.label_39 = QLabel(self.input_fileds_frame_6)
        self.label_39.setGeometry(QRect(0, 260, 111, 21))
        self.label_39.setObjectName("label_39")
        self.label_41 = QLabel(self.input_fileds_frame_6)
        self.label_41.setGeometry(QRect(410, 260, 111, 21))
        self.label_41.setObjectName("label_41")
        self.label_42 = QLabel(self.input_fileds_frame_6)
        self.label_42.setGeometry(QRect(820, 260, 111, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QLabel(self.input_fileds_frame_6)
        self.label_43.setGeometry(QRect(410, 0, 111, 21))
        self.label_43.setObjectName("label_43")
        self.label_49 = QLabel(self.input_fileds_frame_6)
        self.label_49.setGeometry(QRect(820, 0, 111, 21))
        self.label_49.setObjectName("label_49")
        self.label_50 = QLabel(self.input_fileds_frame_6)
        self.label_50.setGeometry(QRect(70, 530, 141, 31))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.input_fileds_frame_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.PipelineView_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_items)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QSize(0, 50))
        self.main_footer.setMaximumSize(QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-color: solid 1px  rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"    color: #fff;\n"
"}")
        self.main_footer.setFrameShape(QFrame.WinPanel)
        self.main_footer.setFrameShadow(QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout_10 = QVBoxLayout(self.main_footer)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QLabel(self.main_footer)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.main_footer, 0, Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "AUTONOMOUS LEARNER DRIVER TESTING SYSTEM"))
        self.accounts_button.setText(_translate("MainWindow", "LOGIN"))
        self.home_button.setText(_translate("MainWindow", "HOME"))
        self.btnaddNewDriver.setText(_translate("MainWindow", "NEW DRIVER"))
        self.btnPriewWin.setText(_translate("MainWindow", "PREVIEW"))
        self.btnAddNewUser.setText(_translate("MainWindow", "NEW USER"))
        self.btnAddNewBooking.setText(_translate("MainWindow", "BOOKING"))
        self.btnShutdown.setText(_translate("MainWindow", "SHUTDOWN"))
        self.settings_button.setText(_translate("MainWindow", "SETTINGS"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.uname_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.password_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Keep me logged in"))
        self.btnLogIn.setText(_translate("MainWindow", "Login"))
        self.label_33.setText(_translate("MainWindow", "LOGIN"))
        self.label_8.setText(_translate("MainWindow", "Full Name"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_9.setText(_translate("MainWindow", "Gender"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Gender"))
        self.btnSaveDriver.setText(_translate("MainWindow", "SAVE"))
        self.label_10.setText(_translate("MainWindow", "D.O.B"))
        self.driverphoneNum.setPlaceholderText(_translate("MainWindow", "Phonebook"))
        self.label_11.setText(_translate("MainWindow", "Phone Number"))
        self.driverEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label_12.setText(_translate("MainWindow", "Email"))
        self.btnCaptureDriverPic.setText(_translate("MainWindow", "CAPTURE"))
        self.label_37.setText(_translate("MainWindow", "Address"))
        self.driverAddress.setPlaceholderText(_translate("MainWindow", "Address"))
        self.label_40.setText(_translate("MainWindow", "NEW DRIVER"))
        self.btnObjDec.setText(_translate("MainWindow", "Object detection"))
        self.btnPause.setText(_translate("MainWindow", "Pause"))
        self.btnView.setText(_translate("MainWindow", "View"))
        self.btnLane.setText(_translate("MainWindow", "Lane detection"))
        self.label_19.setText(_translate("MainWindow", "DRIVER NAME : "))
        self.btnTrafficSigns.setText(_translate("MainWindow", "Traffic Signs"))
        self.label_20.setText(_translate("MainWindow", "TASK PROCESSED :"))
        self.label_21.setText(_translate("MainWindow", "LANE KEEPING  :"))
        self.label_22.setText(_translate("MainWindow", "TRAFFIC LIGHTS  :"))
        self.label_23.setText(_translate("MainWindow", "STOP SIGN  :"))
        self.label_24.setText(_translate("MainWindow", "SPEED  :"))
        self.lanekeeping.setText(_translate("MainWindow", "PENDING"))
        self.lights.setText(_translate("MainWindow", "PENDING"))
        self.speeding.setText(_translate("MainWindow", "PENDING"))
        self.stopsign.setText(_translate("MainWindow", "PENDING"))
        self.Totalpoints.setText(_translate("MainWindow", "1000"))
        self.label_34.setText(_translate("MainWindow", "POINTS : "))
        self.testDeciscion.setText(_translate("MainWindow", "PENDING"))
        self.label_36.setText(_translate("MainWindow", "TEST DECISION :"))
        self.Drivernamelbl.setText(_translate("MainWindow", "driver name"))
        self.btnTrafficLights.setText(_translate("MainWindow", "Traffic Lights"))
        self.label_45.setText(_translate("MainWindow", "MAX SPEED :"))
        self.label_46.setText(_translate("MainWindow", "HEADING :"))
        self.label_47.setText(_translate("MainWindow", "MAX ACCELERATION :"))
        self.label_48.setText(_translate("MainWindow", "DISTANCE COVERED :"))
        self.maxSpeedlbl.setText(_translate("MainWindow", "0.0 m/s"))
        self.headinglbl.setText(_translate("MainWindow", "0.0 deg"))
        self.maxAccellbl.setText(_translate("MainWindow", "0.0 m/s^2"))
        self.distanceCovlbl.setText(_translate("MainWindow", "0.0 m"))
        self.BtnprocessResults.setText(_translate("MainWindow", "Process Results"))
        self.label_16.setText(_translate("MainWindow", "DISTANCE PLOT :"))
        self.label_18.setText(_translate("MainWindow", "ACCELERATION PLOT :"))
        self.label_35.setText(_translate("MainWindow", "ACCELERATION PLOT :"))
        self.label_44.setText(_translate("MainWindow", "SPEED VARIATION PLOT :"))
        self.btnPipelineView_2.setText(_translate("MainWindow", "Pipeline View"))
        self.label_13.setText(_translate("MainWindow", "Full Name :"))
        self.fullname.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Gender :"))
        self.gender.setPlaceholderText(_translate("MainWindow", "Gender"))
        self.label_27.setText(_translate("MainWindow", "Username :"))
        self.uname.setPlaceholderText(_translate("MainWindow", "username"))
        self.label_28.setText(_translate("MainWindow", "Password :"))
        self.password.setPlaceholderText(_translate("MainWindow", "password"))
        self.label_15.setText(_translate("MainWindow", "Email :"))
        self.useremail.setPlaceholderText(_translate("MainWindow", "email"))
        self.label_32.setText(_translate("MainWindow", "NEW USER"))
        self.btnSaveNewUser.setText(_translate("MainWindow", "SAVE"))
        self.label_29.setText(_translate("MainWindow", "Driver ID"))
        self.DriverId.setPlaceholderText(_translate("MainWindow", "Driver ID"))
        self.label_30.setText(_translate("MainWindow", "Booking Date"))
        self.bookDate.setPlaceholderText(_translate("MainWindow", "Booking Date"))
        self.btnSaveBooking.setText(_translate("MainWindow", "SAVE"))
        self.label_31.setText(_translate("MainWindow", "Licence Class"))
        self.licenceClass.setPlaceholderText(_translate("MainWindow", "Licence Class"))
        self.label_3.setText(_translate("MainWindow", "NEW BOOKING"))
        self.label_4.setText(_translate("MainWindow", "Setttings Page"))
        self.label_38.setText(_translate("MainWindow", "Distorted Input"))
        self.btnPausePipeline.setText(_translate("MainWindow", "Pause"))
        self.btnViewPipelineRef.setText(_translate("MainWindow", "Refresh"))
        self.btnTrafficSigns_2.setText(_translate("MainWindow", "Calibarate"))
        self.label_39.setText(_translate("MainWindow", "Yellow and White Filter :"))
        self.label_41.setText(_translate("MainWindow", "HSV Filter"))
        self.label_42.setText(_translate("MainWindow", "Warp Image"))
        self.label_43.setText(_translate("MainWindow", "Undistorted Output :"))
        self.label_49.setText(_translate("MainWindow", "Threshold Image"))
        self.label_50.setText(_translate("MainWindow", "PIPELINE VIEW"))
        self.label_7.setText(_translate("MainWindow", "v 1.0 BY NarroDevs 2020"))
from pyqtgraph import PlotWidget
import nike_app_rc


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
